/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz
      lock_memory: true
      thread_priority: 99

      joint_impedance_controller:
        type: franka_fr3_arm_controllers/JointImpedanceController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

/**:
  joint_impedance_controller:
    ros__parameters:
      p_gains:
        - 130.0
        - 80.0
        - 70.0
        - 60.0
        - 400.0
        - 300.0
        - 200.0
      d_gains:
        - 20.0
        - 10.0
        - 20.0
        - 10.0
        - 8.0
        - 8.0
        - 8.0
      i_gains:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      velocity_filter_alpha: 0.9  # Filters the velocity measured by the robot.
      velocity_limits_scaling: 0.9  # Scales the velocity limits by factor. Used to prevent joint velocity limits errors.
      acceleration_limits: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]  # Acceleration limits for each joint (rad/s^2)
      torque_derivative_limits: [900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0]
